import { useState, useEffect, useCallback, useRef } from "react";
import { useAuth } from "../context/AuthContext";
import { loadDashboardData, saveDashboardData, deleteDashboardData } from "../lib/supabase";
const STATUS_CONFIG = { active: { label: "Active", color: "#22c55e", bg: "rgba(34,197,94,0.1)" }, paused: { label: "Paused", color: "#f59e0b", bg: "rgba(245,158,11,0.1)" }, blocked: { label: "Blocked", color: "#ef4444", bg: "rgba(239,68,68,0.1)" }, completed: { label: "Done", color: "#6366f1", bg: "rgba(99,102,241,0.1)" } };
const PRIORITY_LABELS = ["P0 — Critical", "P1 — High", "P2 — Medium", "P3 — Low", "P4 — Someday"];
const GOAL_COLORS = [{ color: "#c9a227", bg: "rgba(201,162,39,0.12)" },{ color: "#6366f1", bg: "rgba(99,102,241,0.12)" },{ color: "#22c55e", bg: "rgba(34,197,94,0.12)" },{ color: "#ec4899", bg: "rgba(236,72,153,0.12)" },{ color: "#f59e0b", bg: "rgba(245,158,11,0.12)" },{ color: "#06b6d4", bg: "rgba(6,182,212,0.12)" },{ color: "#8b5cf6", bg: "rgba(139,92,246,0.12)" },{ color: "#ef4444", bg: "rgba(239,68,68,0.12)" }];
const generateId = () => Math.random().toString(36).slice(2, 10);
const formatDate = (ts) => !ts ? "—" : new Date(ts).toLocaleDateString("en-US", { month: "short", day: "numeric" });
const formatDateFull = (ts) => !ts ? "—" : new Date(ts).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
const formatDateLong = (ts) => !ts ? "—" : new Date(ts).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric" });
const toDateKey = (d) => { const dd = new Date(d); return `${dd.getFullYear()}-${String(dd.getMonth()+1).padStart(2,"0")}-${String(dd.getDate()).padStart(2,"0")}`; };
const getTodayKey = () => toDateKey(new Date());
const getTomorrowKey = () => { const d = new Date(); d.setDate(d.getDate()+1); return toDateKey(d); };
const dateKeyToDisplay = (key) => { const [y,m,d] = key.split("-").map(Number); return new Date(y,m-1,d).toLocaleDateString("en-US",{weekday:"long",month:"short",day:"numeric"}); };
const dateKeyToTs = (key) => { const [y,m,d] = key.split("-").map(Number); return new Date(y,m-1,d).getTime(); };
const daysUntil = (ts) => { if(!ts) return null; const now=new Date();now.setHours(0,0,0,0);const t=new Date(ts);t.setHours(0,0,0,0);return Math.ceil((t-now)/86400000); };
const daysBetween = (a,b) => (!a||!b)?null:Math.round(Math.abs(b-a)/86400000);
const getGreeting = () => { const h=new Date().getHours(); return h<12?"Good morning":h<17?"Good afternoon":"Good evening"; };
const EA_COLORS = [{ color: "#06b6d4", bg: "rgba(6,182,212,0.12)" },{ color: "#8b5cf6", bg: "rgba(139,92,246,0.12)" },{ color: "#ec4899", bg: "rgba(236,72,153,0.12)" },{ color: "#f59e0b", bg: "rgba(245,158,11,0.12)" },{ color: "#22c55e", bg: "rgba(34,197,94,0.12)" },{ color: "#ef4444", bg: "rgba(239,68,68,0.12)" },{ color: "#c9a227", bg: "rgba(201,162,39,0.12)" },{ color: "#6366f1", bg: "rgba(99,102,241,0.12)" }];
const defaultData = { projects:[], goals:[], eas:[], snapshots:[], reflections:[], ideas:[], workBlocks:{}, routines:{} };
const emptyProject = { name:"", goal:"", status:"active", priority:2, progress:0, nextAction:"", milestones:[], logs:[], goalIds:[], eaId:"" };
const emptyGoal = { name:"", description:"", timeframe:"" };
const emptyEa = { name:"", description:"", scope:"" };
const font = `'DM Sans', sans-serif`;
const mono = `'JetBrains Mono', monospace`;
const C = { bg:"#0f1117", surface:"#181b23", surfaceHover:"#1e2230", border:"#2a2e3a", borderLight:"#353a4a", text:"#e8eaf0", textMuted:"#8b90a0", textDim:"#5a5f72", accent:"#c9a227", accentDim:"rgba(201,162,39,0.12)", accentText:"#e8c94a", green:"#22c55e", red:"#ef4444", amber:"#f59e0b" };

function ProgressBar({value,height=4,color=C.accent}){return <div style={{width:"100%",height,background:C.border,borderRadius:height/2,overflow:"hidden"}}><div style={{width:`${Math.min(100,Math.max(0,value))}%`,height:"100%",background:color,borderRadius:height/2,transition:"width 0.4s ease"}}/></div>;}
function Badge({children,color,bg}){return <span style={{display:"inline-block",fontSize:11,fontWeight:600,letterSpacing:"0.04em",textTransform:"uppercase",color,background:bg,padding:"3px 8px",borderRadius:4,fontFamily:font}}>{children}</span>;}
function Button({children,onClick,variant="primary",size="md",style:xs={},disabled}){const base={fontFamily:font,fontWeight:600,cursor:disabled?"default":"pointer",border:"none",borderRadius:6,transition:"all 0.15s ease",opacity:disabled?0.4:1,display:"inline-flex",alignItems:"center",gap:6};const sz={sm:{fontSize:12,padding:"6px 12px"},md:{fontSize:13,padding:"8px 16px"}};const vr={primary:{background:C.accent,color:"#0f1117"},secondary:{background:C.surfaceHover,color:C.text,border:`1px solid ${C.border}`},ghost:{background:"transparent",color:C.textMuted},danger:{background:"rgba(239,68,68,0.15)",color:"#ef4444"}};return <button onClick={disabled?undefined:onClick} style={{...base,...sz[size],...vr[variant],...xs}}>{children}</button>;}
function Input({value,onChange,placeholder,type="text",style:xs={}}){return <input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={{fontFamily:font,fontSize:13,color:C.text,background:C.bg,border:`1px solid ${C.border}`,borderRadius:6,padding:"8px 12px",outline:"none",width:"100%",boxSizing:"border-box",...xs}}/>;}
function TextArea({value,onChange,placeholder,rows=3,style:xs={}}){return <textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={rows} style={{fontFamily:font,fontSize:13,color:C.text,background:C.bg,border:`1px solid ${C.border}`,borderRadius:6,padding:"8px 12px",outline:"none",width:"100%",boxSizing:"border-box",resize:"vertical",lineHeight:1.5,...xs}}/>;}
function Select({value,onChange,options}){return <select value={value} onChange={e=>onChange(e.target.value)} style={{fontFamily:font,fontSize:13,color:C.text,background:C.bg,border:`1px solid ${C.border}`,borderRadius:6,padding:"8px 12px",outline:"none",width:"100%",boxSizing:"border-box",cursor:"pointer"}}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>;}
function Modal({open,onClose,title,children,width=540}){if(!open)return null;return <div onClick={onClose} style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(0,0,0,0.6)",display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div onClick={e=>e.stopPropagation()} style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:12,width:"100%",maxWidth:width,maxHeight:"85vh",overflow:"auto",padding:24}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h3 style={{margin:0,fontSize:16,fontWeight:700,color:C.text,fontFamily:font}}>{title}</h3><button onClick={onClose} style={{background:"none",border:"none",color:C.textMuted,fontSize:20,cursor:"pointer",padding:4,lineHeight:1}}>×</button></div>{children}</div></div>;}
function FieldLabel({children}){return <label style={{display:"block",fontSize:11,fontWeight:600,letterSpacing:"0.05em",textTransform:"uppercase",color:C.textMuted,marginBottom:6,fontFamily:font}}>{children}</label>;}
function GoalTag({goal,colorIdx,small}){const gc=GOAL_COLORS[colorIdx%GOAL_COLORS.length];return <span style={{display:"inline-block",fontSize:small?10:11,fontWeight:600,color:gc.color,background:gc.bg,padding:small?"2px 6px":"3px 8px",borderRadius:4,fontFamily:font,whiteSpace:"nowrap"}}>{goal.name}</span>;}
function GoalMultiSelect({goals,selectedIds,onChange}){const toggle=id=>onChange(selectedIds.includes(id)?selectedIds.filter(x=>x!==id):[...selectedIds,id]);if(!goals.length)return <div style={{fontSize:12,color:C.textDim,fontStyle:"italic"}}>No goals yet.</div>;return <div style={{display:"flex",flexWrap:"wrap",gap:6}}>{goals.map((g,i)=>{const gc=GOAL_COLORS[i%GOAL_COLORS.length];const sel=selectedIds.includes(g.id);return <button key={g.id} onClick={()=>toggle(g.id)} style={{fontFamily:font,fontSize:12,fontWeight:600,color:sel?gc.color:C.textDim,background:sel?gc.bg:"transparent",border:`1.5px solid ${sel?gc.color:C.border}`,borderRadius:6,padding:"5px 10px",cursor:"pointer"}}>{g.name}</button>;})}</div>;}
function EaTag({ea,colorIdx,small}){const ec=EA_COLORS[colorIdx%EA_COLORS.length];return <span style={{display:"inline-block",fontSize:small?10:11,fontWeight:600,color:ec.color,background:ec.bg,padding:small?"2px 6px":"3px 8px",borderRadius:4,fontFamily:font,whiteSpace:"nowrap"}}>{ea.name}</span>;}
function EaSelect({eas,selectedId,onChange}){if(!eas.length)return <div style={{fontSize:12,color:C.textDim,fontStyle:"italic"}}>No EAs yet.</div>;return <div style={{display:"flex",flexWrap:"wrap",gap:6}}>{eas.map((ea,i)=>{const ec=EA_COLORS[i%EA_COLORS.length];const sel=selectedId===ea.id;return <button key={ea.id} onClick={()=>onChange(sel?"":ea.id)} style={{fontFamily:font,fontSize:12,fontWeight:600,color:sel?ec.color:C.textDim,background:sel?ec.bg:"transparent",border:`1.5px solid ${sel?ec.color:C.border}`,borderRadius:6,padding:"5px 10px",cursor:"pointer"}}>{ea.name}</button>;})}</div>;}
function StatCard({label,value,color}){return <div style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:8,padding:14,textAlign:"center"}}><div style={{fontSize:22,fontWeight:700,color:color||C.accent,fontFamily:mono}}>{value}</div><div style={{fontSize:11,color:C.textDim,textTransform:"uppercase",letterSpacing:"0.05em",marginTop:2,fontFamily:font}}>{label}</div></div>;}
function DeltaChip({value,suffix="%"}){if(!value)return <span style={{fontSize:12,fontFamily:mono,color:C.textDim}}>—</span>;const p=value>0;return <span style={{fontSize:12,fontWeight:700,fontFamily:mono,color:p?C.green:C.red,background:p?"rgba(34,197,94,0.1)":"rgba(239,68,68,0.1)",padding:"2px 7px",borderRadius:4}}>{p?"+":""}{value}{suffix}</span>;}
function SH({children,color=C.accent,icon}){return <div style={{fontSize:12,fontWeight:700,color,textTransform:"uppercase",letterSpacing:"0.05em",marginBottom:12,fontFamily:font}}>{icon&&<span style={{marginRight:6}}>{icon}</span>}{children}</div>;}

function ProjectCard({project,goals,eas,onClick}){const sc=STATUS_CONFIG[project.status];const nextMs=(project.milestones||[]).find(m=>!m.completed);const du=nextMs?daysUntil(nextMs.deadline):null;const pGoals=(project.goalIds||[]).map(gid=>goals.find(g=>g.id===gid)).filter(Boolean);const gim={};goals.forEach((g,i)=>{gim[g.id]=i;});const linkedEa=project.eaId?(eas||[]).find(e=>e.id===project.eaId):null;const eaIdx=linkedEa?(eas||[]).indexOf(linkedEa):0;return <div onClick={onClick} style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:10,padding:18,cursor:"pointer",transition:"all 0.15s ease",borderLeft:`3px solid ${sc.color}`}} onMouseEnter={e=>e.currentTarget.style.background=C.surfaceHover} onMouseLeave={e=>e.currentTarget.style.background=C.surface}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:8}}><div style={{flex:1,minWidth:0}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4,flexWrap:"wrap"}}><span style={{fontSize:11,fontFamily:mono,color:C.textDim,fontWeight:600}}>{PRIORITY_LABELS[project.priority]?.split(" — ")[0]}</span><Badge color={sc.color} bg={sc.bg}>{sc.label}</Badge>{pGoals.map(g=><GoalTag key={g.id} goal={g} colorIdx={gim[g.id]} small/>)}{linkedEa&&<EaTag ea={linkedEa} colorIdx={eaIdx} small/>}</div><h4 style={{margin:0,fontSize:15,fontWeight:700,color:C.text}}>{project.name}</h4></div><span style={{fontSize:20,fontWeight:700,fontFamily:mono,color:C.accent,marginLeft:12}}>{project.progress}%</span></div><ProgressBar value={project.progress} color={sc.color}/>{project.nextAction&&<div style={{marginTop:10,fontSize:12,color:C.textMuted}}><span style={{color:C.accentText,fontWeight:600}}>Next →</span> {project.nextAction}</div>}{nextMs&&<div style={{marginTop:6,fontSize:11,color:du!==null&&du<=3?C.red:C.textDim}}>⏱ {nextMs.name} — {du===0?"Today":du===1?"Tomorrow":du!=null?`${du}d`:""} ({formatDate(nextMs.deadline)})</div>}</div>;}

function ProjectDetail({project,goals,eas,onUpdate,onBack,onDelete}){const[editing,setEditing]=useState(false);const[draft,setDraft]=useState({...project});const[newLog,setNewLog]=useState("");const[newLogHours,setNewLogHours]=useState("");const[newMs,setNewMs]=useState({name:"",deadline:""});const[editingNA,setEditingNA]=useState(false);const[naDraft,setNaDraft]=useState("");useEffect(()=>{setDraft({...project});setEditing(false);},[project.id]);const sc=STATUS_CONFIG[project.status];const doneMs=(project.milestones||[]).filter(m=>m.completed).length;const totalMs=(project.milestones||[]).length;const gim={};goals.forEach((g,i)=>{gim[g.id]=i;});const pGoals=(project.goalIds||[]).map(gid=>goals.find(g=>g.id===gid)).filter(Boolean);const linkedEa=project.eaId?(eas||[]).find(e=>e.id===project.eaId):null;const eaIdx=linkedEa?(eas||[]).indexOf(linkedEa):0;const saveEdit=()=>{onUpdate({...draft,progress:Number(draft.progress)||0,priority:Number(draft.priority)});setEditing(false);};const addLog=()=>{if(!newLog.trim())return;const entry={id:generateId(),note:newLog.trim(),date:Date.now()};const h=parseInt(newLogHours);if(h>0)entry.hours=h;onUpdate({...project,logs:[entry,...(project.logs||[])]});setNewLog("");setNewLogHours("");};const addMs=()=>{if(!newMs.name.trim())return;onUpdate({...project,milestones:[...(project.milestones||[]),{id:generateId(),name:newMs.name.trim(),deadline:newMs.deadline?new Date(newMs.deadline).getTime():null,completed:false}]});setNewMs({name:"",deadline:""});};const toggleMs=mId=>onUpdate({...project,milestones:(project.milestones||[]).map(m=>m.id===mId?{...m,completed:!m.completed}:m)});const deleteMs=mId=>onUpdate({...project,milestones:(project.milestones||[]).filter(m=>m.id!==mId)});const deleteLog=lId=>onUpdate({...project,logs:(project.logs||[]).filter(l=>l.id!==lId)});
return <div><button onClick={onBack} style={{background:"none",border:"none",color:C.textMuted,fontSize:13,cursor:"pointer",fontFamily:font,padding:0,marginBottom:16}}>← Back</button><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:20}}><div><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:6,flexWrap:"wrap"}}><Badge color={sc.color} bg={sc.bg}>{sc.label}</Badge><span style={{fontSize:11,fontFamily:mono,color:C.textDim}}>{PRIORITY_LABELS[project.priority]}</span>{pGoals.map(g=><GoalTag key={g.id} goal={g} colorIdx={gim[g.id]}/>)}{linkedEa&&<EaTag ea={linkedEa} colorIdx={eaIdx}/>}</div><h2 style={{margin:0,fontSize:22,fontWeight:700,color:C.text}}>{project.name}</h2>{project.goal&&<p style={{margin:"6px 0 0",fontSize:13,color:C.textMuted}}>{project.goal}</p>}</div><div style={{display:"flex",gap:8,flexShrink:0}}><Button variant="secondary" size="sm" onClick={()=>{setDraft({...project});setEditing(true);}}>Edit</Button><Button variant="danger" size="sm" onClick={onDelete}>Delete</Button></div></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(3, 1fr)",gap:12,marginBottom:24}}><StatCard label="Progress" value={`${project.progress}%`}/><StatCard label="Milestones" value={`${doneMs}/${totalMs}`}/><StatCard label="Logs" value={`${(project.logs||[]).length}`}/></div>
<div style={{display:"flex",alignItems:"center",gap:10,marginTop:10}}><input type="range" min="0" max="100" value={project.progress} onChange={e=>onUpdate({...project,progress:Number(e.target.value)})} style={{flex:1,accentColor:C.accent,cursor:"pointer",height:6}}/><span style={{fontSize:13,fontWeight:700,fontFamily:mono,color:C.accent,minWidth:36,textAlign:"right"}}>{project.progress}%</span></div>
<div style={{marginTop:16,padding:14,background:C.accentDim,border:"1px solid rgba(201,162,39,0.2)",borderRadius:8}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:editingNA?8:4}}><div style={{fontSize:11,fontWeight:600,color:C.accent,textTransform:"uppercase",letterSpacing:"0.05em"}}>Next Action</div>{!editingNA&&<button onClick={()=>{setNaDraft(project.nextAction||"");setEditingNA(true);}} style={{background:"none",border:"none",color:C.textMuted,cursor:"pointer",fontSize:12,fontFamily:font,padding:"2px 6px"}}>Edit</button>}</div>{editingNA?<div><Input value={naDraft} onChange={setNaDraft} placeholder="What's the next step?"/><div style={{display:"flex",gap:8,marginTop:8,justifyContent:"flex-end"}}><Button variant="secondary" size="sm" onClick={()=>setEditingNA(false)}>Cancel</Button><Button variant="primary" size="sm" onClick={()=>{onUpdate({...project,nextAction:naDraft.trim()});setEditingNA(false);}}>Save</Button></div></div>:<div style={{fontSize:14,color:project.nextAction?C.text:C.textDim,fontStyle:project.nextAction?"normal":"italic"}}>{project.nextAction||"No next action set"}</div>}</div>
<div style={{marginTop:28}}><SH>Milestones</SH>{(project.milestones||[]).map(m=>{const du=daysUntil(m.deadline);return <div key={m.id} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 0",borderBottom:`1px solid ${C.border}`}}><button onClick={()=>toggleMs(m.id)} style={{width:18,height:18,borderRadius:4,border:`1.5px solid ${m.completed?C.accent:C.borderLight}`,background:m.completed?C.accent:"transparent",cursor:"pointer",flexShrink:0,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,color:"#0f1117"}}>{m.completed?"✓":""}</button><span style={{flex:1,fontSize:13,color:m.completed?C.textDim:C.text,textDecoration:m.completed?"line-through":"none"}}>{m.name}</span>{m.deadline&&<span style={{fontSize:11,fontFamily:mono,color:!m.completed&&du!==null&&du<=3?C.red:C.textDim}}>{formatDate(m.deadline)}</span>}<button onClick={()=>deleteMs(m.id)} style={{background:"none",border:"none",color:C.textDim,cursor:"pointer",fontSize:14,padding:2}}>×</button></div>;})}<div style={{display:"flex",gap:8,marginTop:10,alignItems:"center"}}><Input value={newMs.name} onChange={v=>setNewMs(s=>({...s,name:v}))} placeholder="New milestone..." style={{flex:1}}/><div style={{position:"relative"}}><button onClick={()=>{const el=document.getElementById("ms-date-picker");if(el)el.showPicker?.();}} style={{background:C.bg,border:`1px solid ${C.border}`,borderRadius:6,padding:"8px 10px",cursor:"pointer",color:newMs.deadline?C.text:C.textDim,fontFamily:font,fontSize:12,display:"flex",alignItems:"center",gap:4,whiteSpace:"nowrap"}}><span>📅</span>{newMs.deadline?new Date(newMs.deadline+"T00:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"}):"Date"}{newMs.deadline&&<span onClick={e=>{e.stopPropagation();setNewMs(s=>({...s,deadline:""}));}} style={{marginLeft:4,color:C.textDim,cursor:"pointer"}}>×</span>}</button><input id="ms-date-picker" type="date" value={newMs.deadline} onChange={e=>setNewMs(s=>({...s,deadline:e.target.value}))} style={{position:"absolute",top:0,left:0,width:"100%",height:"100%",opacity:0,cursor:"pointer"}}/></div><Button variant="secondary" size="sm" onClick={addMs}>Add</Button></div></div>
<div style={{marginTop:28}}><SH>Latest Progress</SH><div style={{display:"flex",gap:8,marginBottom:14}}><TextArea value={newLog} onChange={setNewLog} placeholder="Log progress, notes, blockers..." rows={2} style={{flex:1}}/><div style={{display:"flex",flexDirection:"column",gap:4,alignSelf:"flex-end"}}><input type="number" min="0" max="99" value={newLogHours} onChange={e=>setNewLogHours(e.target.value)} placeholder="h" style={{width:40,padding:"6px 4px",background:C.bg,border:`1px solid ${C.border}`,borderRadius:6,color:C.text,fontFamily:mono,fontSize:12,textAlign:"center"}}/><Button variant="primary" size="sm" onClick={addLog}>Log</Button></div></div>{(project.logs||[]).slice(0,20).map(l=><div key={l.id} style={{padding:"8px 0",borderBottom:`1px solid ${C.border}`,display:"flex",gap:10}}><span style={{fontSize:11,fontFamily:mono,color:C.textDim,whiteSpace:"nowrap",paddingTop:2}}>{formatDateFull(l.date)}</span>{l.hours>0&&<span style={{fontSize:11,fontFamily:mono,color:C.accent,whiteSpace:"nowrap",paddingTop:2,fontWeight:600}}>{l.hours}h</span>}<span style={{flex:1,fontSize:13,color:C.textMuted,lineHeight:1.5}}>{l.note}</span><button onClick={()=>deleteLog(l.id)} style={{background:"none",border:"none",color:C.textDim,cursor:"pointer",fontSize:14,padding:2,flexShrink:0}}>×</button></div>)}{!(project.logs||[]).length&&<div style={{fontSize:13,color:C.textDim,fontStyle:"italic"}}>No entries yet.</div>}</div>
<Modal open={editing} onClose={()=>setEditing(false)} title="Edit Project"><div style={{display:"flex",flexDirection:"column",gap:14}}><div><FieldLabel>Project Name</FieldLabel><Input value={draft.name} onChange={v=>setDraft(s=>({...s,name:v}))}/></div><div><FieldLabel>Description</FieldLabel><TextArea value={draft.goal||""} onChange={v=>setDraft(s=>({...s,goal:v}))} rows={2}/></div><div><FieldLabel>Linked Goals</FieldLabel><GoalMultiSelect goals={goals} selectedIds={draft.goalIds||[]} onChange={v=>setDraft(s=>({...s,goalIds:v}))}/></div><div><FieldLabel>Executive Assistant</FieldLabel><EaSelect eas={eas||[]} selectedId={draft.eaId||""} onChange={v=>setDraft(s=>({...s,eaId:v}))}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:12}}><div><FieldLabel>Status</FieldLabel><Select value={draft.status} onChange={v=>setDraft(s=>({...s,status:v}))} options={Object.entries(STATUS_CONFIG).map(([k,v])=>({value:k,label:v.label}))}/></div><div><FieldLabel>Priority</FieldLabel><Select value={draft.priority} onChange={v=>setDraft(s=>({...s,priority:v}))} options={PRIORITY_LABELS.map((l,i)=>({value:i,label:l}))}/></div><div><FieldLabel>Progress {draft.progress}%</FieldLabel><input type="range" min="0" max="100" value={draft.progress} onChange={e=>setDraft(s=>({...s,progress:Number(e.target.value)}))} style={{width:"100%",accentColor:C.accent,cursor:"pointer"}}/></div></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:8}}><Button variant="secondary" onClick={()=>setEditing(false)}>Cancel</Button><Button variant="primary" onClick={saveEdit}>Save</Button></div></div></Modal></div>;}

function GoalsView({goals,projects,onAddGoal,onDeleteGoal,onUpdateGoal,onReorderGoals,onSelectProject}){const[showAdd,setShowAdd]=useState(false);const[draft,setDraft]=useState({...emptyGoal});const[editGoalId,setEditGoalId]=useState(null);const[editDraft,setEditDraft]=useState({...emptyGoal});const[dragIdx,setDragIdx]=useState(null);const[overIdx,setOverIdx]=useState(null);const handleAdd=()=>{if(!draft.name.trim())return;onAddGoal({...draft,id:generateId(),createdAt:Date.now()});setDraft({...emptyGoal});setShowAdd(false);};const startEditGoal=(g)=>{setEditGoalId(g.id);setEditDraft({name:g.name,description:g.description||"",timeframe:g.timeframe||""});};const saveEditGoal=()=>{if(!editDraft.name.trim())return;onUpdateGoal(editGoalId,editDraft);setEditGoalId(null);};const handleDragStart=(e,i)=>{setDragIdx(i);e.dataTransfer.effectAllowed="move";};const handleDragOver=(e,i)=>{e.preventDefault();e.dataTransfer.dropEffect="move";setOverIdx(i);};const handleDrop=(e,i)=>{e.preventDefault();if(dragIdx!==null&&dragIdx!==i)onReorderGoals(dragIdx,i);setDragIdx(null);setOverIdx(null);};const handleDragEnd=()=>{setDragIdx(null);setOverIdx(null);};
return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24}}><h2 style={{margin:0,fontSize:20,fontWeight:700}}>Goals & Strategy Map</h2><Button variant="primary" size="sm" onClick={()=>setShowAdd(true)}>+ New Goal</Button></div>
{!goals.length&&<div style={{textAlign:"center",padding:"60px 20px"}}><div style={{fontSize:32,marginBottom:12}}>🎯</div><div style={{fontSize:14,color:C.textMuted,marginBottom:16}}>Define what you're working towards.</div><Button variant="primary" onClick={()=>setShowAdd(true)}>First Goal</Button></div>}
{goals.map((g,gi)=>{const gc=GOAL_COLORS[gi%GOAL_COLORS.length];const linked=projects.filter(p=>(p.goalIds||[]).includes(g.id));const actL=linked.filter(p=>p.status==="active");const avg=linked.length?Math.round(linked.reduce((s,p)=>s+p.progress,0)/linked.length):0;const allDone=linked.length>0&&linked.every(p=>p.status==="completed");const noAct=!actL.length&&!allDone;
return <div key={g.id} draggable onDragStart={e=>handleDragStart(e,gi)} onDragOver={e=>handleDragOver(e,gi)} onDrop={e=>handleDrop(e,gi)} onDragEnd={handleDragEnd} style={{marginBottom:20,background:C.surface,border:`1px solid ${overIdx===gi?C.accent:C.border}`,borderRadius:10,borderLeft:`3px solid ${gc.color}`,opacity:dragIdx===gi?0.5:1,cursor:"grab",transition:"border-color 0.15s ease, opacity 0.15s ease"}}><div style={{padding:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div><h3 style={{margin:0,fontSize:16,fontWeight:700,color:gc.color}}>{g.name}</h3>{g.description&&<p style={{margin:"4px 0 0",fontSize:13,color:C.textMuted}}>{g.description}</p>}{g.timeframe&&<span style={{fontSize:11,fontFamily:mono,color:C.textDim}}>{g.timeframe}</span>}</div><div style={{display:"flex",gap:8,alignItems:"center",flexShrink:0,marginLeft:12}}><span style={{fontSize:22,fontWeight:700,fontFamily:mono,color:gc.color}}>{avg}%</span><button onClick={()=>startEditGoal(g)} style={{background:"none",border:"none",color:C.textDim,cursor:"pointer",fontSize:14,padding:2}} title="Edit goal">&#9998;</button><button onClick={()=>onDeleteGoal(g.id)} style={{background:"none",border:"none",color:C.textDim,cursor:"pointer",fontSize:16,padding:2}}>×</button></div></div><div style={{marginTop:12}}><ProgressBar value={avg} height={5} color={gc.color}/></div>{noAct&&linked.length>0&&<div style={{marginTop:10,fontSize:12,color:C.amber,fontWeight:600}}>⚠ No active projects</div>}{noAct&&!linked.length&&<div style={{marginTop:10,fontSize:12,color:C.textDim,fontStyle:"italic"}}>No projects linked.</div>}{allDone&&<div style={{marginTop:10,fontSize:12,color:C.green,fontWeight:600}}>✓ All completed</div>}{linked.length>0&&<div style={{marginTop:14,display:"flex",flexDirection:"column",gap:6}}>{linked.sort((a,b)=>a.priority-b.priority).map(p=>{const psc=STATUS_CONFIG[p.status];return <div key={p.id} onClick={()=>onSelectProject(p.id)} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 10px",borderRadius:6,background:C.bg,cursor:"pointer"}} onMouseEnter={e=>e.currentTarget.style.background=C.surfaceHover} onMouseLeave={e=>e.currentTarget.style.background=C.bg}><span style={{fontSize:10,fontFamily:mono,color:C.textDim,fontWeight:600,width:22}}>{PRIORITY_LABELS[p.priority]?.split(" ")[0]}</span><Badge color={psc.color} bg={psc.bg}>{psc.label}</Badge><span style={{flex:1,fontSize:13,fontWeight:600,color:C.text}}>{p.name}</span><span style={{fontSize:12,fontFamily:mono,color:C.textDim}}>{p.progress}%</span><div style={{width:60}}><ProgressBar value={p.progress} height={3} color={psc.color}/></div></div>;})}</div>}</div></div>;})}
{(()=>{const orphans=projects.filter(p=>!(p.goalIds||[]).length||!(p.goalIds||[]).some(gid=>goals.find(g=>g.id===gid)));if(!orphans.length)return null;return <div style={{marginTop:28}}><SH color={C.amber} icon="⚠">Unlinked Projects</SH>{orphans.map(p=>{const psc=STATUS_CONFIG[p.status];return <div key={p.id} onClick={()=>onSelectProject(p.id)} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 10px",marginBottom:4,borderRadius:6,background:C.surface,border:`1px solid ${C.border}`,cursor:"pointer"}}><Badge color={psc.color} bg={psc.bg}>{psc.label}</Badge><span style={{flex:1,fontSize:13,fontWeight:600,color:C.text}}>{p.name}</span><span style={{fontSize:12,fontFamily:mono,color:C.textDim}}>{p.progress}%</span></div>;})}</div>;})()}
<Modal open={showAdd} onClose={()=>setShowAdd(false)} title="New Goal"><div style={{display:"flex",flexDirection:"column",gap:14}}><div><FieldLabel>Goal Name</FieldLabel><Input value={draft.name} onChange={v=>setDraft(s=>({...s,name:v}))} placeholder="e.g. Launch SaaS product"/></div><div><FieldLabel>Description</FieldLabel><TextArea value={draft.description} onChange={v=>setDraft(s=>({...s,description:v}))} rows={2}/></div><div><FieldLabel>Timeframe</FieldLabel><Input value={draft.timeframe} onChange={v=>setDraft(s=>({...s,timeframe:v}))} placeholder="e.g. Q2 2026"/></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:8}}><Button variant="secondary" onClick={()=>setShowAdd(false)}>Cancel</Button><Button variant="primary" onClick={handleAdd}>Create</Button></div></div></Modal>
<Modal open={!!editGoalId} onClose={()=>setEditGoalId(null)} title="Edit Goal"><div style={{display:"flex",flexDirection:"column",gap:14}}><div><FieldLabel>Goal Name</FieldLabel><Input value={editDraft.name} onChange={v=>setEditDraft(s=>({...s,name:v}))}/></div><div><FieldLabel>Description</FieldLabel><TextArea value={editDraft.description} onChange={v=>setEditDraft(s=>({...s,description:v}))} rows={2}/></div><div><FieldLabel>Timeframe</FieldLabel><Input value={editDraft.timeframe} onChange={v=>setEditDraft(s=>({...s,timeframe:v}))}/></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:8}}><Button variant="secondary" onClick={()=>setEditGoalId(null)}>Cancel</Button><Button variant="primary" onClick={saveEditGoal}>Save</Button></div></div></Modal></div>;}

function EAsView({eas,projects,onAddEa,onDeleteEa,onUpdateEa,onReorderEas,onSelectProject}){const[showAdd,setShowAdd]=useState(false);const[draft,setDraft]=useState({...emptyEa});const[editEaId,setEditEaId]=useState(null);const[editDraft,setEditDraft]=useState({...emptyEa});const[dragIdx,setDragIdx]=useState(null);const[overIdx,setOverIdx]=useState(null);const handleAdd=()=>{if(!draft.name.trim())return;onAddEa({...draft,id:generateId(),createdAt:Date.now()});setDraft({...emptyEa});setShowAdd(false);};const startEditEa=(ea)=>{setEditEaId(ea.id);setEditDraft({name:ea.name,description:ea.description||"",scope:ea.scope||""});};const saveEditEa=()=>{if(!editDraft.name.trim())return;onUpdateEa(editEaId,editDraft);setEditEaId(null);};const handleDragStart=(e,i)=>{setDragIdx(i);e.dataTransfer.effectAllowed="move";};const handleDragOver=(e,i)=>{e.preventDefault();e.dataTransfer.dropEffect="move";setOverIdx(i);};const handleDrop=(e,i)=>{e.preventDefault();if(dragIdx!==null&&dragIdx!==i)onReorderEas(dragIdx,i);setDragIdx(null);setOverIdx(null);};const handleDragEnd=()=>{setDragIdx(null);setOverIdx(null);};
return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24}}><h2 style={{margin:0,fontSize:20,fontWeight:700}}>Executive Assistants</h2><Button variant="primary" size="sm" onClick={()=>setShowAdd(true)}>+ New EA</Button></div>
{!eas.length&&<div style={{textAlign:"center",padding:"60px 20px"}}><div style={{fontSize:32,marginBottom:12}}>🤖</div><div style={{fontSize:14,color:C.textMuted,marginBottom:16}}>Define your Executive Assistants.</div><Button variant="primary" onClick={()=>setShowAdd(true)}>First EA</Button></div>}
{eas.map((ea,ei)=>{const ec=EA_COLORS[ei%EA_COLORS.length];const linked=projects.filter(p=>p.eaId===ea.id);const actL=linked.filter(p=>p.status==="active");const avg=linked.length?Math.round(linked.reduce((s,p)=>s+p.progress,0)/linked.length):0;const allDone=linked.length>0&&linked.every(p=>p.status==="completed");const noAct=!actL.length&&!allDone;
return <div key={ea.id} draggable onDragStart={e=>handleDragStart(e,ei)} onDragOver={e=>handleDragOver(e,ei)} onDrop={e=>handleDrop(e,ei)} onDragEnd={handleDragEnd} style={{marginBottom:20,background:C.surface,border:`1px solid ${overIdx===ei?C.accent:C.border}`,borderRadius:10,borderLeft:`3px solid ${ec.color}`,opacity:dragIdx===ei?0.5:1,cursor:"grab",transition:"border-color 0.15s ease, opacity 0.15s ease"}}><div style={{padding:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div><h3 style={{margin:0,fontSize:16,fontWeight:700,color:ec.color}}>{ea.name}</h3>{ea.description&&<p style={{margin:"4px 0 0",fontSize:13,color:C.textMuted}}>{ea.description}</p>}{ea.scope&&<span style={{fontSize:11,fontFamily:mono,color:C.textDim}}>{ea.scope}</span>}</div><div style={{display:"flex",gap:8,alignItems:"center",flexShrink:0,marginLeft:12}}><span style={{fontSize:22,fontWeight:700,fontFamily:mono,color:ec.color}}>{avg}%</span><button onClick={()=>startEditEa(ea)} style={{background:"none",border:"none",color:C.textDim,cursor:"pointer",fontSize:14,padding:2}} title="Edit EA">&#9998;</button><button onClick={()=>onDeleteEa(ea.id)} style={{background:"none",border:"none",color:C.textDim,cursor:"pointer",fontSize:16,padding:2}}>×</button></div></div><div style={{marginTop:12}}><ProgressBar value={avg} height={5} color={ec.color}/></div>{noAct&&linked.length>0&&<div style={{marginTop:10,fontSize:12,color:C.amber,fontWeight:600}}>⚠ No active projects</div>}{noAct&&!linked.length&&<div style={{marginTop:10,fontSize:12,color:C.textDim,fontStyle:"italic"}}>No projects linked.</div>}{allDone&&<div style={{marginTop:10,fontSize:12,color:C.green,fontWeight:600}}>✓ All completed</div>}{linked.length>0&&<div style={{marginTop:14,display:"flex",flexDirection:"column",gap:6}}>{linked.sort((a,b)=>a.priority-b.priority).map(p=>{const psc=STATUS_CONFIG[p.status];return <div key={p.id} onClick={()=>onSelectProject(p.id)} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 10px",borderRadius:6,background:C.bg,cursor:"pointer"}} onMouseEnter={e=>e.currentTarget.style.background=C.surfaceHover} onMouseLeave={e=>e.currentTarget.style.background=C.bg}><span style={{fontSize:10,fontFamily:mono,color:C.textDim,fontWeight:600,width:22}}>{PRIORITY_LABELS[p.priority]?.split(" ")[0]}</span><Badge color={psc.color} bg={psc.bg}>{psc.label}</Badge><span style={{flex:1,fontSize:13,fontWeight:600,color:C.text}}>{p.name}</span><span style={{fontSize:12,fontFamily:mono,color:C.textDim}}>{p.progress}%</span><div style={{width:60}}><ProgressBar value={p.progress} height={3} color={psc.color}/></div></div>;})}</div>}</div></div>;})}
{(()=>{const unassigned=projects.filter(p=>!p.eaId||!eas.find(e=>e.id===p.eaId));if(!unassigned.length)return null;return <div style={{marginTop:28}}><SH color={C.amber} icon="⚠">Unassigned Projects</SH>{unassigned.map(p=>{const psc=STATUS_CONFIG[p.status];return <div key={p.id} onClick={()=>onSelectProject(p.id)} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 10px",marginBottom:4,borderRadius:6,background:C.surface,border:`1px solid ${C.border}`,cursor:"pointer"}}><Badge color={psc.color} bg={psc.bg}>{psc.label}</Badge><span style={{flex:1,fontSize:13,fontWeight:600,color:C.text}}>{p.name}</span><span style={{fontSize:12,fontFamily:mono,color:C.textDim}}>{p.progress}%</span></div>;})}</div>;})()}
<Modal open={showAdd} onClose={()=>setShowAdd(false)} title="New Executive Assistant"><div style={{display:"flex",flexDirection:"column",gap:14}}><div><FieldLabel>EA Name</FieldLabel><Input value={draft.name} onChange={v=>setDraft(s=>({...s,name:v}))} placeholder="e.g. Personal EA"/></div><div><FieldLabel>Description</FieldLabel><TextArea value={draft.description} onChange={v=>setDraft(s=>({...s,description:v}))} rows={2}/></div><div><FieldLabel>Scope</FieldLabel><Input value={draft.scope} onChange={v=>setDraft(s=>({...s,scope:v}))} placeholder="e.g. Personal life, health, finance"/></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:8}}><Button variant="secondary" onClick={()=>setShowAdd(false)}>Cancel</Button><Button variant="primary" onClick={handleAdd}>Create</Button></div></div></Modal>
<Modal open={!!editEaId} onClose={()=>setEditEaId(null)} title="Edit Executive Assistant"><div style={{display:"flex",flexDirection:"column",gap:14}}><div><FieldLabel>EA Name</FieldLabel><Input value={editDraft.name} onChange={v=>setEditDraft(s=>({...s,name:v}))}/></div><div><FieldLabel>Description</FieldLabel><TextArea value={editDraft.description} onChange={v=>setEditDraft(s=>({...s,description:v}))} rows={2}/></div><div><FieldLabel>Scope</FieldLabel><Input value={editDraft.scope} onChange={v=>setEditDraft(s=>({...s,scope:v}))}/></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:8}}><Button variant="secondary" onClick={()=>setEditEaId(null)}>Cancel</Button><Button variant="primary" onClick={saveEditEa}>Save</Button></div></div></Modal></div>;}


const BLOCK_LABELS=["Work Block 1","Work Block 2","Work Block 3"];
const BLOCK_ICONS=["","",""];
const ROUTINE_LABELS=["Daily Routine 1","Daily Routine 2","Daily Routine 3","Daily Routine 4"];

function RoutineBlock({index,habits,completions,todayKey,onAddHabit,onDeleteHabit,onToggleHabit}){const[open,setOpen]=useState(false);const[newName,setNewName]=useState("");const slotHabits=habits.filter(h=>h.slot===index);const addH=()=>{if(!newName.trim())return;onAddHabit({id:generateId(),name:newName.trim(),slot:index});setNewName("");};
return <div><button onClick={()=>setOpen(!open)} style={{width:"100%",display:"flex",alignItems:"center",gap:8,padding:"10px 14px",background:"transparent",border:`1px dashed ${C.border}`,borderRadius:8,cursor:"pointer",fontFamily:font,fontSize:12,fontWeight:500,color:C.textDim,transition:"all 0.15s ease"}} onMouseEnter={e=>e.currentTarget.style.borderColor=C.textDim} onMouseLeave={e=>e.currentTarget.style.borderColor=C.border}><span style={{transform:open?"rotate(90deg)":"rotate(0deg)",transition:"transform 0.15s",fontSize:10}}>▶</span>{ROUTINE_LABELS[index]}{slotHabits.length>0&&<span style={{fontSize:11,fontFamily:mono,color:C.textDim,marginLeft:"auto"}}>{slotHabits.filter(h=>(completions[todayKey]||{})[h.id]).length}/{slotHabits.length}</span>}</button>
{open&&<div style={{padding:"10px 14px",background:C.surface,border:`1px solid ${C.border}`,borderTop:"none",borderRadius:"0 0 8px 8px",marginTop:-1}}><div style={{display:"flex",flexWrap:"wrap",gap:6,marginBottom:slotHabits.length?10:0}}>{slotHabits.map(h=>{const done=(completions[todayKey]||{})[h.id];return <div key={h.id} style={{display:"inline-flex",alignItems:"center",gap:6,padding:"5px 10px",background:done?"rgba(34,197,94,0.1)":C.bg,border:`1px solid ${done?"rgba(34,197,94,0.3)":C.border}`,borderRadius:6}}><button onClick={()=>onToggleHabit(h.id,todayKey)} style={{width:16,height:16,borderRadius:4,border:`1.5px solid ${done?C.green:C.borderLight}`,background:done?C.green:"transparent",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,color:"#0f1117",flexShrink:0,padding:0}}>{done?"✓":""}</button><span style={{fontSize:12,fontWeight:500,color:done?C.green:C.text,fontFamily:font}}>{h.name}</span><button onClick={()=>onDeleteHabit(h.id)} style={{background:"none",border:"none",color:C.textDim,cursor:"pointer",fontSize:12,padding:0,marginLeft:2,lineHeight:1}}>×</button></div>;})}</div><div style={{display:"flex",gap:8}}><input value={newName} onChange={e=>setNewName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addH();}}} placeholder="New habit name..." style={{fontFamily:font,fontSize:13,color:C.text,background:C.bg,border:`1px solid ${C.border}`,borderRadius:6,padding:"8px 12px",outline:"none",flex:1,boxSizing:"border-box"}}/><Button variant="secondary" size="sm" onClick={addH}>Add</Button></div></div>}
</div>;}

function HabitTrackerView({routines}){const habits=(routines?.habits)||[];const completions=(routines?.completions)||{};if(!habits.length)return <div><h2 style={{margin:"0 0 8px",fontSize:22,fontWeight:700,color:C.text}}>☑️ Tracker</h2><p style={{fontSize:13,color:C.textMuted,marginBottom:24}}>Track your daily habits over time.</p><div style={{textAlign:"center",padding:"60px 20px",background:C.surface,border:`1px solid ${C.border}`,borderRadius:10}}><div style={{fontSize:14,color:C.textMuted}}>No habits yet. Add habits in the Planning section.</div></div></div>;
const todayKey=getTodayKey();const allDays=Object.keys(completions).filter(dk=>dk<=todayKey).sort((a,b)=>b.localeCompare(a));const days=allDays.length?allDays:[todayKey];
return <div><h2 style={{margin:"0 0 8px",fontSize:22,fontWeight:700,color:C.text}}>☑️ Tracker</h2><p style={{fontSize:13,color:C.textMuted,marginBottom:24}}>Track your daily habits over time.</p>
<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontFamily:font,fontSize:12}}>
<thead><tr><th style={{textAlign:"left",padding:"8px 12px",borderBottom:`2px solid ${C.border}`,color:C.textMuted,fontWeight:600,fontSize:11,textTransform:"uppercase",letterSpacing:"0.05em",position:"sticky",left:0,background:C.bg,zIndex:1,minWidth:100}}>Date</th>{habits.map(h=><th key={h.id} style={{padding:"8px 10px",borderBottom:`2px solid ${C.border}`,color:C.text,fontWeight:600,fontSize:11,textTransform:"uppercase",letterSpacing:"0.03em",textAlign:"center",minWidth:80}}>{h.name}</th>)}</tr></thead>
<tbody>{days.map(dk=>{const isToday=dk===todayKey;const isPast=dk<todayKey;const dayComp=completions[dk]||{};return <tr key={dk} style={{background:isToday?C.accentDim:"transparent"}}><td style={{padding:"6px 12px",borderBottom:`1px solid ${C.border}`,color:isToday?C.accent:C.textMuted,fontFamily:mono,fontSize:11,fontWeight:isToday?700:400,whiteSpace:"nowrap",position:"sticky",left:0,background:isToday?C.accentDim:C.bg,zIndex:1}}>{isToday?"Today":new Date(dk+"T00:00:00").toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})}</td>{habits.map(h=>{const done=dayComp[h.id];return <td key={h.id} style={{padding:"6px 10px",borderBottom:`1px solid ${C.border}`,textAlign:"center"}}>{done?<span style={{color:C.green,fontSize:14,fontWeight:700}}>✓</span>:isPast?<span style={{color:C.textDim,fontSize:14,fontWeight:700}}>✗</span>:<span style={{color:C.textDim}}>—</span>}</td>;})}</tr>;})}</tbody>
</table></div></div>;}

function PlanningView({projects,goals,workBlocks,routines,onUpdateBlocks,onUpdateRoutines,onSelectProject}){
const [showExtraDays,setShowExtraDays]=useState(false);
const todayKey=getTodayKey();const tomorrowKey=getTomorrowKey();
const baseDays=[{key:todayKey,label:"Today",sub:dateKeyToDisplay(todayKey),isToday:true},{key:tomorrowKey,label:"Tomorrow",sub:dateKeyToDisplay(tomorrowKey),isToday:false}];
const extraDays=[];if(showExtraDays){for(let i=2;i<=7;i++){const d=new Date();d.setDate(d.getDate()+i);const k=toDateKey(d);extraDays.push({key:k,label:d.toLocaleDateString("en-US",{weekday:"long"}),sub:dateKeyToDisplay(k),isToday:false});}}
const days=[...baseDays,...extraDays];
const activeProjects=projects.filter(p=>p.status==="active"||p.status==="paused");
const gim={};goals.forEach((g,i)=>{gim[g.id]=i;});
const getBlock=(dk,bi)=>(workBlocks[dk]||{})[`b${bi}`]||"";
const setBlock=(dk,bi,pid)=>{const dd={...(workBlocks[dk]||{})};dd[`b${bi}`]=pid;onUpdateBlocks({...workBlocks,[dk]:dd});};
const getProject=id=>projects.find(p=>p.id===id);
const habits=(routines?.habits)||[];const completions=(routines?.completions)||{};
const addHabit=h=>onUpdateRoutines({...routines,habits:[...habits,h]});
const deleteHabit=hid=>onUpdateRoutines({...routines,habits:habits.filter(h=>h.id!==hid)});
const toggleHabit=(hid,dk)=>{const dc={...(completions[dk]||{})};dc[hid]=!dc[hid];onUpdateRoutines({...routines,completions:{...completions,[dk]:dc}});};

const renderWorkBlock=(block,day)=>{const proj=block.pid?getProject(block.pid):null;const sc=proj?STATUS_CONFIG[proj.status]:null;const projGoals=proj?(proj.goalIds||[]).map(gid=>goals.find(g=>g.id===gid)).filter(Boolean):[];
return <div key={`wb${block.idx}`} style={{background:C.surface,border:`1px solid ${proj?C.borderLight:C.border}`,borderRadius:10,padding:16,borderLeft:proj?`3px solid ${sc.color}`:`3px solid ${C.border}`}}>
<div style={{display:"flex",alignItems:"center",gap:10,marginBottom:10}}><span style={{fontSize:18}}>{BLOCK_ICONS[block.idx]}</span><span style={{fontSize:13,fontWeight:700,color:C.text,flex:1}}>{BLOCK_LABELS[block.idx]}</span>{proj&&<button onClick={()=>setBlock(day.key,block.idx,"")} style={{background:"none",border:"none",color:C.textDim,cursor:"pointer",fontSize:14,padding:"2px 6px"}}>✕</button>}</div>
<select value={block.pid} onChange={e=>setBlock(day.key,block.idx,e.target.value)} style={{fontFamily:font,fontSize:13,color:block.pid?C.text:C.textDim,background:C.bg,border:`1px solid ${C.border}`,borderRadius:6,padding:"10px 12px",width:"100%",boxSizing:"border-box",cursor:"pointer",outline:"none"}}><option value="">— Select a project —</option>{activeProjects.map(p=><option key={p.id} value={p.id}>{PRIORITY_LABELS[p.priority]?.split(" ")[0]} · {p.name} ({p.progress}%)</option>)}</select>
{proj&&<div onClick={()=>onSelectProject(proj.id)} style={{marginTop:12,padding:12,background:C.bg,borderRadius:8,cursor:"pointer"}} onMouseEnter={e=>e.currentTarget.style.background=C.surfaceHover} onMouseLeave={e=>e.currentTarget.style.background=C.bg}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6,flexWrap:"wrap"}}><Badge color={sc.color} bg={sc.bg}>{sc.label}</Badge><span style={{fontSize:11,fontFamily:mono,color:C.textDim}}>{PRIORITY_LABELS[proj.priority]?.split(" — ")[0]}</span>{projGoals.map(g=><GoalTag key={g.id} goal={g} colorIdx={gim[g.id]} small/>)}</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{fontSize:14,fontWeight:700,color:C.text}}>{proj.name}</span><span style={{fontSize:14,fontWeight:700,fontFamily:mono,color:C.accent}}>{proj.progress}%</span></div><ProgressBar value={proj.progress} height={4} color={sc.color}/>{proj.nextAction&&<div style={{marginTop:8,fontSize:12,color:C.accentText}}>→ {proj.nextAction}</div>}</div>}
</div>;};

return <div><div style={{marginBottom:24}}><h2 style={{margin:0,fontSize:22,fontWeight:700,color:C.text}}>Daily Planning</h2><p style={{margin:"4px 0 0",fontSize:13,color:C.textMuted}}>The Boss recommends. You decide. Assign one project per work block.</p></div>
{days.map(day=>{const dayBlocks=[0,1,2].map(i=>({idx:i,pid:getBlock(day.key,i)}));const filled=dayBlocks.filter(b=>b.pid).length;
return <div key={day.key} style={{marginBottom:28}}><div style={{display:"flex",alignItems:"baseline",gap:10,marginBottom:14}}><span style={{fontSize:16,fontWeight:700,color:day.isToday?C.accent:C.text}}>{day.label}</span><span style={{fontSize:12,color:C.textDim,fontFamily:mono}}>{day.sub}</span><span style={{fontSize:11,color:filled===3?C.green:C.textDim,fontFamily:mono,marginLeft:"auto"}}>{filled}/3 planned</span></div>
<div style={{display:"flex",flexDirection:"column",gap:10}}>
<RoutineBlock index={0} habits={habits} completions={completions} todayKey={day.key} onAddHabit={addHabit} onDeleteHabit={deleteHabit} onToggleHabit={toggleHabit}/>
{renderWorkBlock(dayBlocks[0],day)}
<RoutineBlock index={1} habits={habits} completions={completions} todayKey={day.key} onAddHabit={addHabit} onDeleteHabit={deleteHabit} onToggleHabit={toggleHabit}/>
{renderWorkBlock(dayBlocks[1],day)}
<RoutineBlock index={2} habits={habits} completions={completions} todayKey={day.key} onAddHabit={addHabit} onDeleteHabit={deleteHabit} onToggleHabit={toggleHabit}/>
{renderWorkBlock(dayBlocks[2],day)}
<RoutineBlock index={3} habits={habits} completions={completions} todayKey={day.key} onAddHabit={addHabit} onDeleteHabit={deleteHabit} onToggleHabit={toggleHabit}/>
</div></div>;})}
<button onClick={()=>setShowExtraDays(!showExtraDays)} style={{display:"flex",alignItems:"center",justifyContent:"center",gap:6,width:"100%",padding:"10px 0",marginTop:4,background:C.surface,border:`1px solid ${C.border}`,borderRadius:8,color:C.textMuted,fontSize:13,fontWeight:500,fontFamily:font,cursor:"pointer"}}>{showExtraDays?"▲ Hide extra days":"▼ Show 6 more days"}</button>
</div>;}

function ScheduleView({projects,goals,workBlocks,routines,onUpdateRoutines}){
const todayKey=getTodayKey();const habits=(routines?.habits)||[];const completions=(routines?.completions)||{};const gim={};goals.forEach((g,i)=>{gim[g.id]=i;});
const toggleHabit=(hid)=>{const dc={...(completions[todayKey]||{})};dc[hid]=!dc[hid];onUpdateRoutines({...routines,completions:{...completions,[todayKey]:dc}});};
const getBlock=(bi)=>(workBlocks[todayKey]||{})[`b${bi}`]||"";const getProject=id=>projects.find(p=>p.id===id);
const slots=[];for(let i=0;i<4;i++){const slotHabits=habits.filter(h=>h.slot===i);if(slotHabits.length>0)slots.push({type:"routine",index:i,habits:slotHabits});if(i<3){const pid=getBlock(i);const proj=pid?getProject(pid):null;if(proj)slots.push({type:"work",index:i,project:proj});}}
const todayDisplay=dateKeyToDisplay(todayKey);
if(!slots.length)return <div><div style={{marginBottom:24}}><h2 style={{margin:0,fontSize:22,fontWeight:700,color:C.text}}>Today's Schedule</h2><p style={{margin:"4px 0 0",fontSize:13,color:C.textMuted}}>{todayDisplay}</p></div><div style={{textAlign:"center",padding:"60px 20px",background:C.surface,border:`1px solid ${C.border}`,borderRadius:10}}><div style={{fontSize:14,color:C.textMuted}}>Nothing planned for today. Set up your day in Planning.</div></div></div>;
return <div><div style={{marginBottom:24}}><h2 style={{margin:0,fontSize:22,fontWeight:700,color:C.text}}>Today's Schedule</h2><p style={{margin:"4px 0 0",fontSize:13,color:C.textMuted}}>{todayDisplay}</p></div>
<div style={{display:"flex",flexDirection:"column",gap:10}}>{slots.map((slot)=>{if(slot.type==="routine"){const dayComp=completions[todayKey]||{};const doneCount=slot.habits.filter(h=>dayComp[h.id]).length;return <div key={`r${slot.index}`} style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:10,padding:16}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:10}}><span style={{fontSize:13,fontWeight:700,color:C.text}}>{ROUTINE_LABELS[slot.index]}</span><span style={{fontSize:11,fontFamily:mono,color:doneCount===slot.habits.length?C.green:C.textDim}}>{doneCount}/{slot.habits.length}</span></div><div style={{display:"flex",flexWrap:"wrap",gap:6}}>{slot.habits.map(h=>{const done=dayComp[h.id];return <div key={h.id} onClick={()=>toggleHabit(h.id)} style={{display:"inline-flex",alignItems:"center",gap:6,padding:"5px 10px",background:done?"rgba(34,197,94,0.1)":C.bg,border:`1px solid ${done?"rgba(34,197,94,0.3)":C.border}`,borderRadius:6,cursor:"pointer"}}><div style={{width:16,height:16,borderRadius:4,border:`1.5px solid ${done?C.green:C.borderLight}`,background:done?C.green:"transparent",display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,color:"#0f1117",flexShrink:0}}>{done?"\u2713":""}</div><span style={{fontSize:12,fontWeight:500,color:done?C.green:C.text,fontFamily:font}}>{h.name}</span></div>;})}</div></div>;}
if(slot.type==="work"){const proj=slot.project;const sc=STATUS_CONFIG[proj.status];const projGoals=(proj.goalIds||[]).map(gid=>goals.find(g=>g.id===gid)).filter(Boolean);return <div key={`w${slot.index}`} style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:10,padding:16,borderLeft:`3px solid ${sc.color}`}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><span style={{fontSize:18}}>{BLOCK_ICONS[slot.index]}</span><span style={{fontSize:13,fontWeight:700,color:C.text,flex:1}}>{BLOCK_LABELS[slot.index]}</span></div><div style={{padding:12,background:C.bg,borderRadius:8}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6,flexWrap:"wrap"}}><Badge color={sc.color} bg={sc.bg}>{sc.label}</Badge><span style={{fontSize:11,fontFamily:mono,color:C.textDim}}>{PRIORITY_LABELS[proj.priority]?.split(" \u2014 ")[0]}</span>{projGoals.map(g=><GoalTag key={g.id} goal={g} colorIdx={gim[g.id]} small/>)}</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{fontSize:14,fontWeight:700,color:C.text}}>{proj.name}</span><span style={{fontSize:14,fontWeight:700,fontFamily:mono,color:C.accent}}>{proj.progress}%</span></div><ProgressBar value={proj.progress} height={4} color={sc.color}/>{proj.nextAction&&<div style={{marginTop:8,fontSize:12,color:C.accentText}}>{"\u2192"} {proj.nextAction}</div>}</div></div>;}
return null;})}</div></div>;}

const BOSS_TOOLS=[
{name:"update_project",description:"Update a project's progress, status, next action, name, description, priority, or linked goals",input_schema:{type:"object",properties:{project_id:{type:"string"},name:{type:"string"},goal:{type:"string",description:"Project description"},progress:{type:"number",description:"0-100"},status:{type:"string",enum:["active","paused","blocked","completed"]},priority:{type:"number",description:"0=Critical,1=High,2=Medium,3=Low,4=Someday"},next_action:{type:"string"},goal_ids:{type:"array",items:{type:"string"},description:"Array of goal IDs to link"},ea_id:{type:"string",description:"EA ID to link"}},required:["project_id"]}},
{name:"delete_project",description:"Delete a project",input_schema:{type:"object",properties:{project_id:{type:"string"}},required:["project_id"]}},
{name:"add_project",description:"Create a new project",input_schema:{type:"object",properties:{name:{type:"string"},goal:{type:"string"},priority:{type:"number",description:"0=Critical,1=High,2=Medium,3=Low,4=Someday"},status:{type:"string",enum:["active","paused","blocked","completed"]},next_action:{type:"string"},goal_ids:{type:"array",items:{type:"string"}},ea_id:{type:"string",description:"EA ID to link"}},required:["name"]}},
{name:"add_activity_log",description:"Add an activity log entry to a project",input_schema:{type:"object",properties:{project_id:{type:"string"},note:{type:"string"},hours:{type:"number",description:"Hours spent (whole number, optional)"}},required:["project_id","note"]}},
{name:"delete_activity_log",description:"Delete an activity log entry",input_schema:{type:"object",properties:{project_id:{type:"string"},log_id:{type:"string"}},required:["project_id","log_id"]}},
{name:"add_milestone",description:"Add a milestone to a project",input_schema:{type:"object",properties:{project_id:{type:"string"},name:{type:"string"},deadline:{type:"string",description:"ISO date or empty"}},required:["project_id","name"]}},
{name:"toggle_milestone",description:"Toggle a milestone's completed status",input_schema:{type:"object",properties:{project_id:{type:"string"},milestone_id:{type:"string"}},required:["project_id","milestone_id"]}},
{name:"delete_milestone",description:"Delete a milestone",input_schema:{type:"object",properties:{project_id:{type:"string"},milestone_id:{type:"string"}},required:["project_id","milestone_id"]}},
{name:"add_goal",description:"Create a new goal",input_schema:{type:"object",properties:{name:{type:"string"},description:{type:"string"},timeframe:{type:"string"}},required:["name"]}},
{name:"delete_goal",description:"Delete a goal and unlink it from all projects",input_schema:{type:"object",properties:{goal_id:{type:"string"}},required:["goal_id"]}},
{name:"set_work_block",description:"Assign a project to a work block for a specific day",input_schema:{type:"object",properties:{date_key:{type:"string",description:"YYYY-MM-DD format"},block_index:{type:"number",description:"0, 1, or 2 for Work Block 1-3"},project_id:{type:"string",description:"Project ID or empty string to clear"}},required:["date_key","block_index","project_id"]}},
{name:"add_habit",description:"Add a daily habit to a routine slot",input_schema:{type:"object",properties:{name:{type:"string"},slot:{type:"number",description:"0-3 for Daily Routine 1-4"}},required:["name","slot"]}},
{name:"delete_habit",description:"Delete a daily habit",input_schema:{type:"object",properties:{habit_id:{type:"string"}},required:["habit_id"]}},
{name:"toggle_habit",description:"Toggle a habit's completion for a specific day",input_schema:{type:"object",properties:{habit_id:{type:"string"},date_key:{type:"string",description:"YYYY-MM-DD format"}},required:["habit_id","date_key"]}},
{name:"save_reflection",description:"Save a reflection entry",input_schema:{type:"object",properties:{went_well:{type:"string"},improve:{type:"string"},next_focus:{type:"string"},freeform:{type:"string"}},required:[]}},
{name:"add_ea",description:"Create a new Executive Assistant",input_schema:{type:"object",properties:{name:{type:"string"},description:{type:"string"},scope:{type:"string"}},required:["name"]}},
{name:"delete_ea",description:"Delete an EA and unlink it from all projects",input_schema:{type:"object",properties:{ea_id:{type:"string"}},required:["ea_id"]}},
{name:"update_ea",description:"Update an EA's name, description, or scope",input_schema:{type:"object",properties:{ea_id:{type:"string"},name:{type:"string"},description:{type:"string"},scope:{type:"string"}},required:["ea_id"]}}
];

function BossView({data,onSave}){
const[messages,setMessages]=useState([]);const[input,setInput]=useState("");const[loading,setLoading]=useState(false);const[apiKey,setApiKey]=useState(()=>localStorage.getItem("boss_api_key")||"");const[keyInput,setKeyInput]=useState("");const[showKey,setShowKey]=useState(false);const chatEnd=useRef(null);const inputRef=useRef(null);
useEffect(()=>{chatEnd.current?.scrollIntoView({behavior:"smooth"});},[messages]);

const projects=data?.projects||[];const goals=data?.goals||[];const eas=data?.eas||[];const workBlocks=data?.workBlocks||{};const routines=data?.routines||{};const reflections=data?.reflections||[];
const todayKey=getTodayKey();const todayBlocks=workBlocks[todayKey]||{};

const buildSystem=()=>{const tKey=getTodayKey();const tmKey=getTomorrowKey();
const pData=projects.map(p=>({id:p.id,name:p.name,description:p.goal,status:p.status,priority:PRIORITY_LABELS[p.priority],priorityNum:p.priority,progress:p.progress,nextAction:p.nextAction||"",milestones:(p.milestones||[]).map(m=>({id:m.id,name:m.name,completed:m.completed,deadline:m.deadline?formatDateFull(m.deadline):"none"})),recentLogs:(p.logs||[]).slice(0,10).map(l=>({id:l.id,date:formatDateFull(l.date),note:l.note,hours:l.hours||0})),linkedGoalIds:p.goalIds||[],eaId:p.eaId||""}));
const gData=goals.map(g=>{const linked=projects.filter(p=>(p.goalIds||[]).includes(g.id));const avg=linked.length?Math.round(linked.reduce((s,p)=>s+p.progress,0)/linked.length):0;return{id:g.id,name:g.name,description:g.description,timeframe:g.timeframe,avgProgress:avg,projectCount:linked.length};});
const eaData=eas.map(ea=>{const linked=projects.filter(p=>p.eaId===ea.id);const avg=linked.length?Math.round(linked.reduce((s,p)=>s+p.progress,0)/linked.length):0;return{id:ea.id,name:ea.name,description:ea.description,scope:ea.scope,avgProgress:avg,projectCount:linked.length};});
const todayWb=workBlocks[tKey]||{};const tmWb=workBlocks[tmKey]||{};
const fmtBlock=(wb,label)=>{const b=[wb.b0,wb.b1,wb.b2].map((pid,i)=>{const p=pid?projects.find(x=>x.id===pid):null;return`  Block ${i+1}: ${p?`${p.name} (id:${p.id})`:"empty"}`;});return`${label}:\n${b.join("\n")}`;};
const habitData=(routines?.habits||[]).map(h=>({id:h.id,name:h.name,slot:h.slot,slotLabel:ROUTINE_LABELS[h.slot]}));
const todayCompletions=(routines?.completions||{})[tKey]||{};
const habitStatus=habitData.map(h=>({...h,doneToday:!!todayCompletions[h.id]}));
const recentReflections=(reflections||[]).slice(-3).reverse().map(r=>({date:formatDateFull(r.date),wentWell:r.wentWell,improve:r.improve,nextFocus:r.nextFocus,notes:r.freeform}));
return `You are "The Boss" — an authoritative but supportive AI executive assistant for a personal productivity dashboard. You speak directly, give clear actionable advice, and hold the user accountable. You help the user plan their day, discuss next steps, and manage all aspects of their dashboard.

Today: ${new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}
Today's date key: ${tKey}
Tomorrow's date key: ${tmKey}

PROJECTS:
${JSON.stringify(pData,null,2)}

GOALS:
${JSON.stringify(gData,null,2)}

EXECUTIVE ASSISTANTS:
${JSON.stringify(eaData,null,2)}

WORK BLOCKS:
${fmtBlock(todayWb,"Today ("+tKey+")")}
${fmtBlock(tmWb,"Tomorrow ("+tmKey+")")}

DAILY HABITS & ROUTINES (slot 0=before Work Block 1, 1=before WB2, 2=before WB3, 3=after WB3):
${JSON.stringify(habitStatus,null,2)}

RECENT REFLECTIONS:
${JSON.stringify(recentReflections,null,2)}

You have full tools to modify ALL dashboard data: projects, goals, executive assistants, milestones, activity logs, work blocks, daily habits, and reflections. Use them proactively when the user asks you to make changes. Always confirm what you changed.

When discussing planning and daily routines:
- Help the user decide which projects to assign to work blocks
- Suggest habits to add or adjust
- Discuss priorities and what to focus on next
- Be specific — reference actual project names, progress numbers, and deadlines

Keep responses concise and action-oriented.`;};

const executeToolUse=(name,inp)=>{const d=JSON.parse(JSON.stringify(data));
if(name==="update_project"){d.projects=d.projects.map(p=>{if(p.id!==inp.project_id)return p;const u={...p};if(inp.progress!==undefined)u.progress=inp.progress;if(inp.status)u.status=inp.status;if(inp.next_action!==undefined)u.nextAction=inp.next_action;if(inp.name)u.name=inp.name;if(inp.goal!==undefined)u.goal=inp.goal;if(inp.priority!==undefined)u.priority=inp.priority;if(inp.goal_ids)u.goalIds=inp.goal_ids;if(inp.ea_id!==undefined)u.eaId=inp.ea_id;return u;});onSave(d);return"Project updated.";}
if(name==="delete_project"){const pName=(d.projects.find(p=>p.id===inp.project_id)||{}).name;d.projects=d.projects.filter(p=>p.id!==inp.project_id);onSave(d);return`Project "${pName}" deleted.`;}
if(name==="add_project"){const np={id:generateId(),name:inp.name,goal:inp.goal||"",status:inp.status||"active",priority:inp.priority??2,progress:0,nextAction:inp.next_action||"",milestones:[],logs:[],goalIds:inp.goal_ids||[],eaId:inp.ea_id||"",createdAt:Date.now()};d.projects=[...d.projects,np];onSave(d);return`Project "${inp.name}" created (id: ${np.id}).`;}
if(name==="add_activity_log"){d.projects=d.projects.map(p=>{if(p.id!==inp.project_id)return p;const entry={id:generateId(),note:inp.note,date:Date.now()};if(inp.hours>0)entry.hours=Math.round(inp.hours);return{...p,logs:[entry,...(p.logs||[])]};});onSave(d);return"Activity log added.";}
if(name==="delete_activity_log"){d.projects=d.projects.map(p=>{if(p.id!==inp.project_id)return p;return{...p,logs:(p.logs||[]).filter(l=>l.id!==inp.log_id)};});onSave(d);return"Activity log deleted.";}
if(name==="add_milestone"){d.projects=d.projects.map(p=>{if(p.id!==inp.project_id)return p;return{...p,milestones:[...(p.milestones||[]),{id:generateId(),name:inp.name,deadline:inp.deadline?new Date(inp.deadline).getTime():null,completed:false}]};});onSave(d);return"Milestone added.";}
if(name==="toggle_milestone"){d.projects=d.projects.map(p=>{if(p.id!==inp.project_id)return p;return{...p,milestones:(p.milestones||[]).map(m=>m.id===inp.milestone_id?{...m,completed:!m.completed}:m)};});onSave(d);return"Milestone toggled.";}
if(name==="delete_milestone"){d.projects=d.projects.map(p=>{if(p.id!==inp.project_id)return p;return{...p,milestones:(p.milestones||[]).filter(m=>m.id!==inp.milestone_id)};});onSave(d);return"Milestone deleted.";}
if(name==="add_goal"){const ng={id:generateId(),name:inp.name,description:inp.description||"",timeframe:inp.timeframe||"",createdAt:Date.now()};d.goals=[...(d.goals||[]),ng];onSave(d);return`Goal "${inp.name}" created (id: ${ng.id}).`;}
if(name==="delete_goal"){const gName=((d.goals||[]).find(g=>g.id===inp.goal_id)||{}).name;d.goals=(d.goals||[]).filter(g=>g.id!==inp.goal_id);d.projects=d.projects.map(p=>({...p,goalIds:(p.goalIds||[]).filter(gid=>gid!==inp.goal_id)}));onSave(d);return`Goal "${gName}" deleted and unlinked from projects.`;}
if(name==="add_ea"){const ne={id:generateId(),name:inp.name,description:inp.description||"",scope:inp.scope||"",createdAt:Date.now()};d.eas=[...(d.eas||[]),ne];onSave(d);return"EA created (id: "+ne.id+").";}
if(name==="delete_ea"){const eName=((d.eas||[]).find(e=>e.id===inp.ea_id)||{}).name;d.eas=(d.eas||[]).filter(e=>e.id!==inp.ea_id);d.projects=d.projects.map(p=>({...p,eaId:p.eaId===inp.ea_id?"":p.eaId}));onSave(d);return"EA "+(eName||"")+" deleted and unlinked from projects.";}
if(name==="update_ea"){d.eas=(d.eas||[]).map(e=>{if(e.id!==inp.ea_id)return e;const u={...e};if(inp.name)u.name=inp.name;if(inp.description!==undefined)u.description=inp.description;if(inp.scope!==undefined)u.scope=inp.scope;return u;});onSave(d);return"EA updated.";}
if(name==="set_work_block"){const wb={...(d.workBlocks||{})};const dayBlocks={...(wb[inp.date_key]||{})};dayBlocks[`b${inp.block_index}`]=inp.project_id;wb[inp.date_key]=dayBlocks;d.workBlocks=wb;onSave(d);const pName=inp.project_id?(d.projects.find(p=>p.id===inp.project_id)||{}).name:"(cleared)";return`Work Block ${inp.block_index+1} on ${inp.date_key} set to ${pName}.`;}
if(name==="add_habit"){const nh={id:generateId(),name:inp.name,slot:inp.slot};const habits=[...((d.routines||{}).habits||[]),nh];d.routines={...(d.routines||{}),habits};onSave(d);return`Habit "${inp.name}" added to ${ROUTINE_LABELS[inp.slot]}.`;}
if(name==="delete_habit"){const habits=((d.routines||{}).habits||[]).filter(h=>h.id!==inp.habit_id);d.routines={...(d.routines||{}),habits};onSave(d);return"Habit deleted.";}
if(name==="toggle_habit"){const comps={...((d.routines||{}).completions||{})};const dayC={...(comps[inp.date_key]||{})};dayC[inp.habit_id]=!dayC[inp.habit_id];comps[inp.date_key]=dayC;d.routines={...(d.routines||{}),completions:comps};onSave(d);return`Habit toggled for ${inp.date_key}.`;}
if(name==="save_reflection"){const r={id:generateId(),date:Date.now(),wentWell:inp.went_well||"",improve:inp.improve||"",nextFocus:inp.next_focus||"",freeform:inp.freeform||""};d.reflections=[...(d.reflections||[]),r];onSave(d);return"Reflection saved.";}
return"Unknown tool.";};

const sendMessage=async()=>{if(!input.trim()||loading)return;const userMsg={role:"user",content:input.trim()};const newMsgs=[...messages,userMsg];setMessages(newMsgs);setInput("");setLoading(true);
try{let apiMsgs=newMsgs.map(m=>({role:m.role,content:m.content}));let done=false;let assistantText="";
while(!done){const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"x-api-key":apiKey,"anthropic-version":"2023-06-01","content-type":"application/json","anthropic-dangerous-direct-browser-access":"true"},body:JSON.stringify({model:"claude-sonnet-4-6",max_tokens:2048,system:buildSystem(),messages:apiMsgs,tools:BOSS_TOOLS})});
if(!res.ok){const err=await res.text();throw new Error(err);}const body=await res.json();
const textBlocks=body.content.filter(b=>b.type==="text").map(b=>b.text).join("");const toolBlocks=body.content.filter(b=>b.type==="tool_use");
if(textBlocks)assistantText+=textBlocks;
if(toolBlocks.length>0){apiMsgs=[...apiMsgs,{role:"assistant",content:body.content}];
const toolResults=toolBlocks.map(tb=>{const result=executeToolUse(tb.name,tb.input);return{type:"tool_result",tool_use_id:tb.id,content:result};});apiMsgs=[...apiMsgs,{role:"user",content:toolResults}];}else{done=true;}}
setMessages(m=>[...m,{role:"assistant",content:assistantText}]);
}catch(e){setMessages(m=>[...m,{role:"assistant",content:`Error: ${e.message}`}]);}finally{setLoading(false);}};

const saveKey=()=>{localStorage.setItem("boss_api_key",keyInput);setApiKey(keyInput);setShowKey(false);};

if(!apiKey)return <div><h2 style={{margin:"0 0 8px",fontSize:22,fontWeight:700,color:C.text}}>The Boss</h2><p style={{fontSize:13,color:C.textMuted,marginBottom:24}}>Your AI executive assistant. Needs an Anthropic API key to work.</p>
<div style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:10,padding:24,maxWidth:400}}>
<FieldLabel>Anthropic API Key</FieldLabel><input type="password" value={keyInput} onChange={e=>setKeyInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")saveKey();}} placeholder="sk-ant-..." style={{fontFamily:font,fontSize:13,color:C.text,background:C.bg,border:`1px solid ${C.border}`,borderRadius:6,padding:"8px 12px",outline:"none",width:"100%",boxSizing:"border-box",marginBottom:12}}/>
<div style={{fontSize:11,color:C.textDim,marginBottom:12}}>Stored locally in your browser only. Never sent to our servers.</div>
<Button variant="primary" onClick={saveKey}>Save Key</Button></div></div>;

return <div style={{display:"flex",flexDirection:"column",height:"calc(100vh - 120px)"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><div><h2 style={{margin:0,fontSize:22,fontWeight:700,color:C.text}}>The Boss</h2><p style={{margin:"4px 0 0",fontSize:13,color:C.textMuted}}>Your AI executive assistant. Ask anything about your dashboard.</p></div>
<Button variant="ghost" size="sm" onClick={()=>{setShowKey(!showKey);setKeyInput(apiKey);}}>API Key</Button></div>
{showKey&&<div style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:8,padding:12,marginBottom:12,display:"flex",gap:8,alignItems:"center"}}><input type="password" value={keyInput} onChange={e=>setKeyInput(e.target.value)} style={{fontFamily:font,fontSize:13,color:C.text,background:C.bg,border:`1px solid ${C.border}`,borderRadius:6,padding:"6px 10px",outline:"none",flex:1,boxSizing:"border-box"}}/><Button variant="secondary" size="sm" onClick={saveKey}>Update</Button><Button variant="ghost" size="sm" onClick={()=>{localStorage.removeItem("boss_api_key");setApiKey("");setKeyInput("");}}>Remove</Button></div>}
<div style={{flex:1,overflowY:"auto",marginBottom:16,display:"flex",flexDirection:"column",gap:12}}>
{!messages.length&&<div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{textAlign:"center",maxWidth:360}}><div style={{fontSize:32,marginBottom:12}}>👔</div><div style={{fontSize:15,fontWeight:600,color:C.text,marginBottom:8}}>What can I help you with?</div><div style={{fontSize:13,color:C.textMuted,lineHeight:1.6}}>Ask me for a briefing, advice on priorities, help planning your day, or tell me to update your projects.</div>
<div style={{display:"flex",flexWrap:"wrap",gap:6,justifyContent:"center",marginTop:16}}>{["Give me a briefing","Plan my day","What should I focus on today?","Set up my work blocks","Which projects are falling behind?","Let's discuss my daily routine"].map(q=><button key={q} onClick={()=>{setInput(q);setTimeout(()=>inputRef.current?.focus(),0);}} style={{fontFamily:font,fontSize:12,color:C.textMuted,background:C.surface,border:`1px solid ${C.border}`,borderRadius:6,padding:"6px 12px",cursor:"pointer"}} onMouseEnter={e=>e.currentTarget.style.borderColor=C.accent} onMouseLeave={e=>e.currentTarget.style.borderColor=C.border}>{q}</button>)}</div></div></div>}
{messages.map((m,i)=><div key={i} style={{display:"flex",justifyContent:m.role==="user"?"flex-end":"flex-start"}}><div style={{maxWidth:"85%",padding:"10px 14px",borderRadius:10,background:m.role==="user"?C.accentDim:C.surface,border:`1px solid ${m.role==="user"?"rgba(201,162,39,0.2)":C.border}`,fontSize:13,color:C.text,lineHeight:1.6,whiteSpace:"pre-wrap"}}>{m.content}</div></div>)}
{loading&&<div style={{display:"flex",justifyContent:"flex-start"}}><div style={{padding:"10px 14px",borderRadius:10,background:C.surface,border:`1px solid ${C.border}`,fontSize:13,color:C.textDim}}>Thinking...</div></div>}
<div ref={chatEnd}/></div>
<div style={{display:"flex",gap:8}}><input ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage();}}} placeholder="Ask The Boss..." style={{fontFamily:font,fontSize:13,color:C.text,background:C.surface,border:`1px solid ${C.border}`,borderRadius:8,padding:"12px 14px",outline:"none",flex:1,boxSizing:"border-box"}}/><Button variant="primary" onClick={sendMessage} disabled={loading||!input.trim()}>Send</Button></div></div>;}

function createSnapshot(projects,goals){return{id:generateId(),date:Date.now(),projects:projects.map(p=>({id:p.id,name:p.name,status:p.status,progress:p.progress,priority:p.priority,nextAction:p.nextAction,goalIds:p.goalIds||[],msT:(p.milestones||[]).length,msD:(p.milestones||[]).filter(m=>m.completed).length})),goals:goals.map(g=>{const l=projects.filter(p=>(p.goalIds||[]).includes(g.id));return{id:g.id,name:g.name,avg:l.length?Math.round(l.reduce((s,p)=>s+p.progress,0)/l.length):0};})};}

const PROMPTS=["Which project was your biggest win?","Where did you spend time without moving the needle?","Is your priority order still right?","One thing to focus on next week?","Are you avoiding something?"];

function EngineerIdeasView({ideas,onSaveIdea,onUpdateIdea,onDeleteIdea}){
const[text,setText]=useState("");const[editingId,setEditingId]=useState(null);const[editText,setEditText]=useState("");const[copied,setCopied]=useState(null);
const handleSave=()=>{if(!text.trim())return;onSaveIdea({id:generateId(),text:text.trim(),createdAt:Date.now(),updatedAt:Date.now()});setText("");};
const startEdit=(idea)=>{setEditingId(idea.id);setEditText(idea.text);};
const cancelEdit=()=>{setEditingId(null);setEditText("");};
const saveEdit=(id)=>{if(!editText.trim())return;onUpdateIdea(id,editText.trim());setEditingId(null);setEditText("");};
const copyAsMd=(idea)=>{const d=new Date(idea.createdAt);const dateStr=d.toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"});const timeStr=d.toLocaleTimeString("en-US",{hour:"2-digit",minute:"2-digit"});const md=`## Idea - ${dateStr}, ${timeStr}\n\n${idea.text}\n`;navigator.clipboard.writeText(md);setCopied(idea.id);setTimeout(()=>setCopied(null),2000);};
const formatTimestamp=(ts)=>{const d=new Date(ts);return d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})+" at "+d.toLocaleTimeString("en-US",{hour:"2-digit",minute:"2-digit"});};
return <div><div style={{marginBottom:24}}><h2 style={{margin:0,fontSize:22,fontWeight:700,color:C.text}}>Engineer Ideas</h2><p style={{margin:"4px 0 0",fontSize:13,color:C.textMuted}}>Capture ideas as they come. Edit, refine, copy as Markdown.</p></div>
<div style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:10,padding:18,marginBottom:24}}>
<TextArea value={text} onChange={setText} placeholder="Type your idea..." rows={4}/>
<div style={{display:"flex",justifyContent:"flex-end",marginTop:10}}><Button variant="primary" onClick={handleSave} disabled={!text.trim()}>Save Idea</Button></div></div>
{[...ideas].reverse().map(idea=><div key={idea.id} style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:8,padding:16,marginBottom:10}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}>
<div style={{fontSize:12,fontFamily:mono,color:C.textDim}}>{formatTimestamp(idea.createdAt)}{idea.updatedAt&&idea.updatedAt!==idea.createdAt&&<span style={{marginLeft:8}}>(edited {formatTimestamp(idea.updatedAt)})</span>}</div>
<div style={{display:"flex",gap:6}}>
{editingId!==idea.id&&<Button variant="ghost" size="sm" onClick={()=>startEdit(idea)}>Edit</Button>}
<Button variant="ghost" size="sm" onClick={()=>copyAsMd(idea)}>{copied===idea.id?"Copied":"Copy MD"}</Button>
<button onClick={()=>onDeleteIdea(idea.id)} style={{background:"none",border:"none",color:C.textDim,cursor:"pointer",fontSize:14,padding:2}}>x</button>
</div></div>
{editingId===idea.id?<div><TextArea value={editText} onChange={setEditText} rows={4}/><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:8}}><Button variant="secondary" size="sm" onClick={cancelEdit}>Cancel</Button><Button variant="primary" size="sm" onClick={()=>saveEdit(idea.id)}>Save</Button></div></div>:<div style={{fontSize:13,color:C.text,lineHeight:1.6,whiteSpace:"pre-wrap"}}>{idea.text}</div>}
</div>)}
{!ideas.length&&<div style={{textAlign:"center",padding:"60px 20px",background:C.surface,border:`1px solid ${C.border}`,borderRadius:10}}><div style={{fontSize:14,color:C.textMuted}}>No ideas yet. Start typing above.</div></div>}
</div>;}

function ReviewView({projects,workBlocks}){
const todayKey=getTodayKey();const projectIds=new Set(projects.map(p=>p.id));
const days=Object.keys(workBlocks).filter(dk=>dk<=todayKey).sort((a,b)=>b.localeCompare(a));if(!days.includes(todayKey))days.unshift(todayKey);
if(!projects.length)return <div><h2 style={{margin:"0 0 8px",fontSize:22,fontWeight:700,color:C.text}}>Review</h2><p style={{fontSize:13,color:C.textMuted,marginBottom:24}}>Daily project activity overview.</p><div style={{textAlign:"center",padding:"60px 20px",background:C.surface,border:`1px solid ${C.border}`,borderRadius:10}}><div style={{fontSize:14,color:C.textMuted}}>No projects yet.</div></div></div>;
return <div><h2 style={{margin:"0 0 8px",fontSize:22,fontWeight:700,color:C.text}}>Review</h2><p style={{fontSize:13,color:C.textMuted,marginBottom:24}}>Daily project activity overview.</p>
<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontFamily:font,fontSize:12}}>
<thead><tr><th style={{textAlign:"left",padding:"8px 12px",borderBottom:`2px solid ${C.border}`,color:C.textMuted,fontWeight:600,fontSize:11,textTransform:"uppercase",letterSpacing:"0.05em",position:"sticky",left:0,background:C.bg,zIndex:1,minWidth:100}}>Date</th>{projects.map(p=><th key={p.id} style={{padding:"8px 10px",borderBottom:`2px solid ${C.border}`,color:C.text,fontWeight:600,fontSize:11,textTransform:"uppercase",letterSpacing:"0.03em",textAlign:"center",minWidth:80}}>{p.name}</th>)}</tr></thead>
<tbody>{days.map(dk=>{const isToday=dk===todayKey;const dayWb=workBlocks[dk]||{};const dayProjectIds=new Set([dayWb.b0,dayWb.b1,dayWb.b2].filter(Boolean));
return <tr key={dk} style={{background:isToday?C.accentDim:"transparent"}}><td style={{padding:"6px 12px",borderBottom:`1px solid ${C.border}`,color:isToday?C.accent:C.textMuted,fontFamily:mono,fontSize:11,fontWeight:isToday?700:400,whiteSpace:"nowrap",position:"sticky",left:0,background:isToday?C.accentDim:C.bg,zIndex:1}}>{isToday?"Today":new Date(dk+"T00:00:00").toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})}</td>{projects.map(p=>{const inBlock=dayProjectIds.has(p.id);const blocked=p.status==="blocked";return <td key={p.id} style={{padding:"6px 10px",borderBottom:`1px solid ${C.border}`,textAlign:"center",fontSize:16}}>{blocked?"🔴":inBlock?"🟢":"⚪"}</td>;})}</tr>;})}</tbody>
</table></div></div>;}

export default function BossDashboard(){
const { user, signOut } = useAuth();
const[data,setData]=useState(null);const[loading,setLoading]=useState(true);const[view,setView]=useState("planning");const[selectedId,setSelectedId]=useState(null);const[showAdd,setShowAdd]=useState(false);const[newProject,setNewProject]=useState({...emptyProject});const[projDragIdx,setProjDragIdx]=useState(null);const[projOverIdx,setProjOverIdx]=useState(null);
useEffect(()=>{if(!user)return;(async()=>{try{const r=await loadDashboardData(user.id);setData(r||{...defaultData});}catch{setData({...defaultData});}setLoading(false);})();},[user]);
const save=useCallback(async nd=>{setData(nd);try{await saveDashboardData(user.id,nd);}catch(e){console.error("Save:",e);}},[user]);
const projects=data?.projects||[];const goals=data?.goals||[];const eas=data?.eas||[];const snapshots=data?.snapshots||[];const reflections=data?.reflections||[];const workBlocks=data?.workBlocks||{};const routines=data?.routines||{};const selected=projects.find(p=>p.id===selectedId);
const updateProject=u=>save({...data,projects:projects.map(p=>p.id===u.id?u:p)});
const deleteProject=id=>{save({...data,projects:projects.filter(p=>p.id!==id)});setView("projects");setSelectedId(null);};
const addProject=()=>{if(!newProject.name.trim())return;save({...data,projects:[...projects,{...newProject,id:generateId(),priority:Number(newProject.priority),progress:Number(newProject.progress)||0,milestones:[],logs:[],createdAt:Date.now()}]});setNewProject({...emptyProject});setShowAdd(false);};
const reorderProjects=(fi,ti)=>{const np=[...projects];const[m]=np.splice(fi,1);np.splice(ti,0,m);save({...data,projects:np});};
const reorderGoals=(fi,ti)=>{const ng=[...goals];const[m]=ng.splice(fi,1);ng.splice(ti,0,m);save({...data,goals:ng});};
const updateGoal=(id,updates)=>save({...data,goals:goals.map(g=>g.id===id?{...g,...updates}:g)});
const addGoal=g=>save({...data,goals:[...goals,g]});
const deleteGoal=id=>save({...data,goals:goals.filter(g=>g.id!==id),projects:projects.map(p=>({...p,goalIds:(p.goalIds||[]).filter(gid=>gid!==id)}))});
const addEa=ea=>save({...data,eas:[...eas,ea]});
const deleteEa=id=>save({...data,eas:eas.filter(e=>e.id!==id),projects:projects.map(p=>({...p,eaId:p.eaId===id?"":p.eaId}))});
const updateEa=(id,updates)=>save({...data,eas:eas.map(e=>e.id===id?{...e,...updates}:e)});
const reorderEas=(fi,ti)=>{const ne=[...eas];const[m]=ne.splice(fi,1);ne.splice(ti,0,m);save({...data,eas:ne})};
const saveSnapshot=s=>save({...data,snapshots:[...snapshots,s]});
const deleteSnapshot=id=>save({...data,snapshots:snapshots.filter(s=>s.id!==id)});
const saveReflection=r=>save({...data,reflections:[...reflections,r]});
const ideas=data?.ideas||[];
const saveIdea=idea=>save({...data,ideas:[...ideas,idea]});
const updateIdea=(id,newText)=>save({...data,ideas:ideas.map(i=>i.id===id?{...i,text:newText,updatedAt:Date.now()}:i)});
const deleteIdea=id=>save({...data,ideas:ideas.filter(i=>i.id!==id)});
const updateBlocks=wb=>save({...data,workBlocks:wb});const updateRoutines=rt=>save({...data,routines:rt});
const resetAll=async()=>{try{await deleteDashboardData(user.id);}catch{}setData({...defaultData});setView("briefing");setSelectedId(null);};
if(loading)return <div style={{minHeight:"100vh",background:C.bg,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{color:C.textMuted}}>Loading...</span></div>;
const tabs=[{key:"boss",label:"👔 Boss"},{key:"_sep1"},{key:"schedule",label:"📋 Schedule"},{key:"planning",label:"📅 Planning"},{key:"projects",label:"📁 Projects"},{key:"goals",label:"🎯 Goals"},{key:"eas",label:"🤖 EAs"},{key:"_sep2"},{key:"review",label:"📊 Review"},{key:"habits",label:"☑️ Habit Tracker"},{key:"ideas",label:"💡 Engineer Ideas"}];
return <div style={{minHeight:"100vh",background:C.bg,fontFamily:font,color:C.text}}>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet"/>
<div style={{borderBottom:`1px solid ${C.border}`,padding:"14px 24px",display:"flex",justifyContent:"space-between",alignItems:"center",background:C.surface}}>
<div style={{display:"flex",alignItems:"center",gap:16}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:8,height:8,borderRadius:"50%",background:C.accent,boxShadow:`0 0 8px ${C.accent}`}}/><span style={{fontSize:15,fontWeight:700,letterSpacing:"-0.01em"}}>THE JOURNEY</span></div>
<div style={{display:"flex",gap:2,alignItems:"center"}}>{tabs.map(t=>t.key.startsWith("_sep")?<div key={t.key} style={{width:1,height:16,background:C.border,margin:"0 8px"}}/>:<button key={t.key} onClick={()=>{setView(t.key);setSelectedId(null);}} style={{fontFamily:font,fontSize:12,fontWeight:600,color:(view===t.key||(view==="detail"&&t.key==="projects"))?C.accent:C.textMuted,background:(view===t.key||(view==="detail"&&t.key==="projects"))?C.accentDim:"transparent",border:"none",borderRadius:5,padding:"6px 12px",cursor:"pointer",transition:"all 0.15s ease"}}>{t.label}</button>)}</div></div>
<div style={{display:"flex",gap:8}}><Button variant="ghost" size="sm" onClick={resetAll}>Reset</Button><Button variant="ghost" size="sm" onClick={signOut}>Sign Out</Button></div></div>
<div style={{maxWidth:760,margin:"0 auto",padding:"28px 24px"}}>
{view==="boss"&&<BossView data={data} onSave={save}/>}
{view==="schedule"&&<ScheduleView projects={projects} goals={goals} workBlocks={workBlocks} routines={routines} onUpdateRoutines={updateRoutines}/>}
{view==="planning"&&<PlanningView projects={projects} goals={goals} workBlocks={workBlocks} routines={routines} onUpdateBlocks={updateBlocks} onUpdateRoutines={updateRoutines} onSelectProject={id=>{setSelectedId(id);setView("detail");}}/>}
{view==="goals"&&<GoalsView goals={goals} projects={projects} onAddGoal={addGoal} onDeleteGoal={deleteGoal} onUpdateGoal={updateGoal} onReorderGoals={reorderGoals} onSelectProject={id=>{setSelectedId(id);setView("detail");}}/>}
{view==="eas"&&<EAsView eas={eas} projects={projects} onAddEa={addEa} onDeleteEa={deleteEa} onUpdateEa={updateEa} onReorderEas={reorderEas} onSelectProject={id=>{setSelectedId(id);setView("detail");}}/>}
{view==="projects"&&<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h2 style={{margin:0,fontSize:20,fontWeight:700}}>All Projects</h2><div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:12,color:C.textDim,fontFamily:mono}}>{projects.length} total</span><Button variant="primary" size="sm" onClick={()=>setShowAdd(true)}>+ Project</Button></div></div>{!projects.length&&<div style={{textAlign:"center",padding:"60px 20px"}}><div style={{fontSize:14,color:C.textMuted,marginBottom:12}}>No projects yet.</div><Button variant="primary" onClick={()=>setShowAdd(true)}>Add First</Button></div>}<div style={{display:"flex",flexDirection:"column",gap:10}}>{projects.map((p,pi)=><div key={p.id} draggable onDragStart={e=>{setProjDragIdx(pi);e.dataTransfer.effectAllowed="move";}} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect="move";setProjOverIdx(pi);}} onDrop={e=>{e.preventDefault();if(projDragIdx!==null&&projDragIdx!==pi)reorderProjects(projDragIdx,pi);setProjDragIdx(null);setProjOverIdx(null);}} onDragEnd={()=>{setProjDragIdx(null);setProjOverIdx(null);}} style={{opacity:projDragIdx===pi?0.5:1,border:projOverIdx===pi?`2px solid ${C.accent}`:"2px solid transparent",borderRadius:12,transition:"border-color 0.15s ease, opacity 0.15s ease",cursor:"grab"}}><ProjectCard project={p} goals={goals} eas={eas} onClick={()=>{setSelectedId(p.id);setView("detail");}}/></div>)}</div></div>}
{view==="detail"&&selected&&<ProjectDetail project={selected} goals={goals} eas={eas} onUpdate={updateProject} onBack={()=>{setView("projects");setSelectedId(null);}} onDelete={()=>deleteProject(selected.id)}/>}
{view==="review"&&<ReviewView projects={projects} workBlocks={workBlocks}/>}
{view==="ideas"&&<EngineerIdeasView ideas={ideas} onSaveIdea={saveIdea} onUpdateIdea={updateIdea} onDeleteIdea={deleteIdea}/>}
{view==="habits"&&<HabitTrackerView routines={routines}/>}
</div>
<Modal open={showAdd} onClose={()=>setShowAdd(false)} title="New Project"><div style={{display:"flex",flexDirection:"column",gap:14}}><div><FieldLabel>Project Name</FieldLabel><Input value={newProject.name} onChange={v=>setNewProject(s=>({...s,name:v}))} placeholder="e.g. Launch Website"/></div><div><FieldLabel>Description</FieldLabel><TextArea value={newProject.goal} onChange={v=>setNewProject(s=>({...s,goal:v}))} rows={2}/></div><div><FieldLabel>Linked Goals</FieldLabel><GoalMultiSelect goals={goals} selectedIds={newProject.goalIds||[]} onChange={v=>setNewProject(s=>({...s,goalIds:v}))}/></div><div><FieldLabel>Executive Assistant</FieldLabel><EaSelect eas={eas||[]} selectedId={newProject.eaId||""} onChange={v=>setNewProject(s=>({...s,eaId:v}))}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:12}}><div><FieldLabel>Status</FieldLabel><Select value={newProject.status} onChange={v=>setNewProject(s=>({...s,status:v}))} options={Object.entries(STATUS_CONFIG).map(([k,v])=>({value:k,label:v.label}))}/></div><div><FieldLabel>Priority</FieldLabel><Select value={newProject.priority} onChange={v=>setNewProject(s=>({...s,priority:v}))} options={PRIORITY_LABELS.map((l,i)=>({value:i,label:l}))}/></div><div><FieldLabel>Progress %</FieldLabel><Input value={newProject.progress} onChange={v=>setNewProject(s=>({...s,progress:v}))} type="number"/></div></div><div><FieldLabel>Next Action</FieldLabel><Input value={newProject.nextAction} onChange={v=>setNewProject(s=>({...s,nextAction:v}))}/></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:8}}><Button variant="secondary" onClick={()=>setShowAdd(false)}>Cancel</Button><Button variant="primary" onClick={addProject}>Create</Button></div></div></Modal>
</div>;}
